/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as ApiSearchRouteImport } from './routes/api.search'
import { Route as LangLlmsFullDottxtRouteImport } from './routes/$lang.llms-full[.]txt'
import { Route as LangDocsSplatRouteImport } from './routes/$lang.docs.$'
import { Route as LangLlmsDotmdxDocsSplatRouteImport } from './routes/$lang.llms[.]mdx.docs.$'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLlmsFullDottxtRoute = LangLlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => LangRoute,
} as any)
const LangDocsSplatRoute = LangDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => LangRoute,
} as any)
const LangLlmsDotmdxDocsSplatRoute = LangLlmsDotmdxDocsSplatRouteImport.update({
  id: '/llms.mdx/docs/$',
  path: '/llms.mdx/docs/$',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/$lang/llms-full.txt': typeof LangLlmsFullDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/$lang/llms.mdx/docs/$': typeof LangLlmsDotmdxDocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/$lang/llms-full.txt': typeof LangLlmsFullDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/$lang/llms.mdx/docs/$': typeof LangLlmsDotmdxDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/$lang/llms-full.txt': typeof LangLlmsFullDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
  '/$lang/llms.mdx/docs/$': typeof LangLlmsDotmdxDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/docs'
    | '/$lang/llms-full.txt'
    | '/api/search'
    | '/docs/$'
    | '/$lang/'
    | '/$lang/docs/$'
    | '/$lang/llms.mdx/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/$lang/llms-full.txt'
    | '/api/search'
    | '/docs/$'
    | '/$lang'
    | '/$lang/docs/$'
    | '/$lang/llms.mdx/docs/$'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/docs'
    | '/$lang/llms-full.txt'
    | '/api/search'
    | '/docs/$'
    | '/$lang/'
    | '/$lang/docs/$'
    | '/$lang/llms.mdx/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/llms-full.txt': {
      id: '/$lang/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/$lang/llms-full.txt'
      preLoaderRoute: typeof LangLlmsFullDottxtRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/docs/$': {
      id: '/$lang/docs/$'
      path: '/docs/$'
      fullPath: '/$lang/docs/$'
      preLoaderRoute: typeof LangDocsSplatRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/llms.mdx/docs/$': {
      id: '/$lang/llms.mdx/docs/$'
      path: '/llms.mdx/docs/$'
      fullPath: '/$lang/llms.mdx/docs/$'
      preLoaderRoute: typeof LangLlmsDotmdxDocsSplatRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangLlmsFullDottxtRoute: typeof LangLlmsFullDottxtRoute
  LangIndexRoute: typeof LangIndexRoute
  LangDocsSplatRoute: typeof LangDocsSplatRoute
  LangLlmsDotmdxDocsSplatRoute: typeof LangLlmsDotmdxDocsSplatRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangLlmsFullDottxtRoute: LangLlmsFullDottxtRoute,
  LangIndexRoute: LangIndexRoute,
  LangDocsSplatRoute: LangDocsSplatRoute,
  LangLlmsDotmdxDocsSplatRoute: LangLlmsDotmdxDocsSplatRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
